### ISSUE TITLE
feat: automate creating opportunity with only links

### ISSUE THREAD

**Issue by HuiHui1026** [hitesh22rana/OptySys#11]
### Feature request
Add a feature for the organization admins to post opportunity with links only

### Description
* Admins can attach a link of the opportunity posted on linkedIn or any other platform 
* The automation can extract the description and required skills from the originally posted opportunity 
* This feature will reduce the need of manually adding the required fields for posting the opportunity

I hope i explained the feature .Let me know if i should ellaborate about the feature more .This seems a small feature but can be helpful .Do let me know if it matches your interest or not
Thanks

**Comment by hitesh22rana** [comment]
Amazing idea @HuiHui1026 
would surely add this support firstly for the sites like LinkedIn and Internshala.

**Comment by hitesh22rana** [comment]
feature created successfully 🥳 @HuiHui1026
