### ISSUE TITLE
docs: remove unwanted lines from readme

### ISSUE THREAD

**Issue by hitesh22rana** [hitesh22rana/OptySys#12]
remove line:- ``To set up OptySys locally, follow these steps:-``
location:- under **`Table of Contents`** heading from README.md

**Comment by hitesh22rana** [comment]
remove lines:- 
1. ``Streamlining opportunities with efficient matching and automation``
location:- under **`Table of Contents`** heading from README.md

2. `Table of Contents`
location:- under **`Table of Contents`** heading from README.md

**Comment by yashpreet2707** [comment]
I've made a PR, do check it out @hitesh22rana
