### ISSUE TITLE
feat: improve onboarding to the project

### ISSUE THREAD

**Issue by kumarsonsoff3** [hitesh22rana/OptySys#16]
To improve the onboarding of the project, we should add: 

- code of conduct 
- issue templates (YML forms)
- PR templates
- And a greeting action (to make it more collaborative for the new contributors)

For `Code of Conduct`, I recommend adopting [`Contributor Covenant Code of Conduct`](https://github.com/hitesh22rana/OptySys/community/code-of-conduct/new?template=contributor-covenant)

**Comment by hitesh22rana** [comment]
Hey @kumarsonsoff3 this is great.
do u wanna work on this?

**Comment by kumarsonsoff3** [comment]
Sure! Would love to help with this! :)
