### ISSUE TITLE
Web application structure

### ISSUE THREAD

**Issue by hitesh22rana** [hitesh22rana/OptySys#9]

**Comment by hitesh22rana** [comment]
Add the structure for all the screens of the web application and how they are connected with each other in the README.md of frontend folder

**Comment by Aniket1026** [comment]
@hitesh22rana  I would like to work in this issue . If it's still open I'd like to get assigned

**Comment by hitesh22rana** [comment]
> @hitesh22rana I would like to work in this issue . If it's still open I'd like to get assigned

Sure @Aniket1026 go ahead.
Do comment if u need any assistance, would love to help

**Comment by Aniket1026** [comment]
Yes , actually I would like to know the flow for the frontend . Not detailed , only the high level view would be fine for me to get the gist  and propose a intermediate structure

**Comment by hitesh22rana** [comment]
> Yes , actually I would like to know the flow for the frontend . Not detailed , only the high level view would be fine for me to get the gist and propose a intermediate structure

Alrightyyy, let's start,
so basically, the frontend would consist of multiple screens/pages, so the high level structure of this would be something like.
So I want to duplicate this entire thing in the architectural format which can be then added to the **README.md** of the frontend folder, as well as explained.

We have 2 kinds of routes :- **Public Routes and Private Routes**

**Public Routes**
- Home Screen
- Authentication
    - Login
    - Signup

**Private Routes**
- User Details form (It is must and should be filled in order to further authorize the user, as well as to perform some actions)
    - DashBoard
        - Sidebar
            - Joined organizations
                - Publish opportunities
            - Available opportunities
                - View opportunities
                    - Create custom cover-letter
        - Topbar
            - Searchbar
            - Notifications
            - Settings
            - Logout
        - Organizations
            - View organization page
                - join organization
                
I hope this fixes your doubts.
Do ping me if you require any assistance, would love to help 😄

**Comment by Aniket1026** [comment]
> > Yes , actually I would like to know the flow for the frontend . Not detailed , only the high level view would be fine for me to get the gist and propose a intermediate structure
> 
> Alrightyyy, let's start, so basically, the frontend would consist of multiple screens/pages, so the high level structure of this would be something like. So I want to duplicate this entire thing in the architectural format which can be then added to the **README.md** of the frontend folder, as well as explained.
> 
> We have 2 kinds of routes :- **Public Routes and Private Routes**
> 
> **Public Routes**
> 
> * Home Screen
> * Authentication
>   
>   * Login
>   * Signup
> 
> **Private Routes**
> 
> * User Details form (It is must and should be filled in order to further authorize the user, as well as to perform some actions)
>   
>   * DashBoard
>     
>     * Sidebar
>       
>       * Joined organizations
>         
>         * Publish opportunities
>       * Available opportunities
>         
>         * View opportunities
>           
>           * Create custom cover-letter
>     * Topbar
>       
>       * Searchbar
>       * Notifications
>       * Settings
>       * Logout
>     * Organizations
>       
>       * View organization page
>         
>         * join organization
> 
> I hope this fixes your doubts. Do ping me if you require any assistance, would love to help 😄

Thanks for explaining me deeply about the structure . 
Following the instruction I'll try to propose a intermediate hierarchical high level over view for the frontend which can be added in the readme for understanding the frontend structure and also helpful for other contributors 😊
